### ISSUE TITLE
Add sponsorship information for sphereEx

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/acasia2021#114]
We need to update the sponsorship for sphereEx.  
Here is the logo file.
[apache.zip](https://github.com/alc-beijing/acasia2021/files/6884348/apache.zip)

**Comment by tedliu1** [comment]
The logo shouod be added to both ApacheCon @Home and ApacheCon Asia for combined Silver sponsorship. Thanks.

**Comment by tedliu1** [comment]
OK, got it. Will raise the request to ***@***.***

Ted Liu 
 
   在 2021 年 7月 月 27 日週二，時間：22:15 ， Willem Jiang ***@***.***> 寫道：   



The logo shouod be added to both ApacheCon @Home and ApacheCon Asia for combined Silver sponsorship. Thanks.


Hi Ted, this repo only deals with the ApacheCon Asia, we can not update ApacheCon @Home from this repo.
