### ISSUE TITLE
remove or replace the Google Analytics codes in header.html

### ISSUE THREAD

**Issue by jixuan1989** [alc-beijing/acasia2021#5]
Now themes/apachecon/layouts/partials.header.html has Google Analytics codes.

We need to either remove the codes, or change to a new google analytics codes that we can see the dashboard.

**Comment by WillemJiang** [comment]
I just create a new GA code, UA-192418729-1 to help us track the information.
Please let me know you google account if you are interesting about the web access data.

**Comment by WillemJiang** [comment]
The UA id is replaced.
